version: "3.9"

services:
  telemetry-postgres:
    image: postgres:16
    container_name: telemetry-postgres
    environment:
      POSTGRES_DB: telemetrydb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  telemetry-api:
    container_name: telemetry-api
    build:
      context: ./Telemetry.Api
      dockerfile: Dockerfile
    depends_on:
      - telemetry-postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Postgres: Host=telemetry-postgres;Port=5432;Database=telemetrydb;Username=app;Password=app
    ports:
      - "8080:8080"

volumes:
  pg_data:
